sudo: required
language: bash
env:
  global:
    - PACKER_VERSION=1.5.5
    - TF_VERSION=0.12.24
    - TFLINT_VERSION=0.16.0

branches:
  only:
    - ansible-3
    - master

before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash

jobs:
  include:
    - name: check packer configs
      language: generic
      before_install:
        - wget https://releases.hashicorp.com/packer/"$PACKER_VERSION"/packer_"$PACKER_VERSION"_linux_amd64.zip -O /tmp/packer.zip
        - sudo unzip -o /tmp/packer.zip -d /usr/local/bin/
        - ./scripts/install_ansible.sh
#      install:
#       - cd packer
      script:
        - packer validate -var-file=./packer/variables.json.example ./packer/app.json
        - packer validate -var-file=./packer/variables.json.example ./packer/db.json
        - packer validate -var-file=./packer/variables.json.example -syntax-only ./packer/ubuntu16.json

    - name: validate terraform configs
      language: generic
      before_install:
        - ./scripts/install_terraform.sh $TF_VERSION
        - ./scripts/install_tflint.sh $TFLINT_VERSION
      script:
        - cd "$TRAVIS_BUILD_DIR"/terraform/stage
        - terraform init -backend=false
        - terraform validate
        - tflint --var-file=terraform.tfvars.example
        - cd "$TRAVIS_BUILD_DIR"/terraform/prod
        - terraform init -backend=false
        - terraform validate
        - tflint --var-file=terraform.tfvars.example

notifications:
  slack:
    rooms:
      secure: xRKMvmZ60JnQHpQkG/5i+YMmsRaF/FHty0TkvLZYT0KLhdyo8wWH4q4L4QQ989snKgYPXFzqyZrSGtAAs6zR1bSLi9upm/bVU0rjJv/IyTlQ7/E696p1njONAAwuJSO0zyM+GnnGh3ofOTu4Dvwd1pfc/6TLU+0i7CbsT6cKTxcEsPGx599JTkr1OXN3oqD3woL6Dbwxz78OqhAr4J6YwVqMBXaFdwiU8JSayUh7egxwSSLDNH6tViewLxf5cli3RWdimDY4xEi20Z9Zl6cP3JdevCxPyjrVOhHAMUTg4UfbcYg2aRwNM7om62ty/KhcNLSMf2IZdK059skzJb7T9UbL/UgKOInZVsF8BM3vdNDG6JWwmTBQMYVWHoe+ZWiBs9+Qi6eSzvq57lEtv5hGi0vJKlyStcM7fqtLWoCue6jqRrsHT7KCbOZMOeNhqLfYRIRUVs3msSFHCAnLgbbNwWAqrYcWauVAQF0A36+uYZ3kOyZf6EhAyZuF7JcTAOs21F4MY4lZ9m9nvHV3OW/CWy1ofWwdnaGAghLoUczYwcoxZUm6HVNS5uGbfruP4qqPb1X3ljlpgGH5eY+xXOtGKOzNrDKhXyojYU1exXcFtI4/NYoG+CrMwX1p6+UtCwOexGS7KrmcUGHOk6W2TOxW6SHd7dol3nxkv8zov8Pn0PQ=
