- name: Configure App
  hosts: app
  become: true

  vars:
    # see https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html
    db_host: "{{ hostvars[groups['db'][0]]['ansible_internal_host'] }}"

  roles:
    - app
