Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "dbserver" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "10.10.10.10"

    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
        # create group "db" with the only host "dbserver"
        # define variables for "db"
        "db" => ["dbserver"],
        "db:vars" => {"mongo_bind_ip" => "0.0.0.0"}
      }
    end
  end

def nginxConfProvisioning(appPort="9292", serverPort="80")
  return <<STR
listen #{serverPort};
server_name "reddit";
location / {
  proxy_pass http://127.0.0.1:#{appPort};
}
STR
end

$nginx_config =
  config.vm.define "appserver" do |app|
    app.vm.box = "ubuntu/xenial64"
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "10.10.10.20"

    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
        # create group "app" with the only host "appserver"
        # define variables for "app"
        "app" => ["appserver"],
        "app:vars" => {
          "db_host" => "10.10.10.10"
        }
      }
      ansible.extra_vars = {
        "deploy_user" => "vagrant",
        "nginx_sites" => {
            "default" => [nginxConfProvisioning("9292", "80")]
        }
      }
    end
  end
end
